export const OPEN_MODAL_REQUEST = 'OPEN_MODAL_REQUEST';
export const OPEN_MODAL_SUCCESS = 'OPEN_MODAL_SUCCESS';
export const CLOSE_MODAL_REQUEST = 'CLOSE_MODAL_REQUEST';
export const OPEN_MODAL_FAIL = 'OPEN_MODAL_FAIL';
